import TopBar from "@/components/layout/topBar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Quiz | Leaf & Life",
  description: "Generated by create next app",
};

export default function QuizLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen">
      <TopBar />
      {children}
    </div>
  );
}
