export const userFormFields = [
  {
    id: "fullName",
    type: "text",
    label: "Full Name",
    placeholder: "John Doe",
    required: true,
    autoComplete: "name",
    validation: { minLength: 2 },
    icon: "https://res.cloudinary.com/dryw0xncr/image/upload/v1779803555/user-svgrepo-com_lirc9z.svg",
  },
  {
    id: "email",
    type: "email",
    label: "Email Address",
    placeholder: "example@mail.com",
    required: true,
    autoComplete: "email",
    validation: {
      pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
    },
    icon: "https://res.cloudinary.com/dryw0xncr/image/upload/v1779803552/email-1-svgrepo-com_ibgqjf.svg",
  },
  {
    id: "phone",
    type: "tel",
    label: "Phone Number",
    placeholder: "+380 (XX) XXX-XX-XX",
    required: true,
    autoComplete: "tel",
    validation: { mask: "+38\\0 (00) 000-00-00" },
    icon: "https://res.cloudinary.com/dryw0xncr/image/upload/v1779803553/phone-svgrepo-com_f3kqho.svg",
  },
  {
    id: "address",
    type: "text",
    label: "Delivery Address",
    placeholder: "City, Street, Building / Shipping branch",
    required: true,
    autoComplete: "",
    validation: { minLength: 5 },
    icon: "https://res.cloudinary.com/dryw0xncr/image/upload/v1779803550/city-town-residents-svgrepo-com_yt9h4i.svg",
  },
];
