import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Noto_Serif } from "next/font/google";
import "./globals.css";
import { Amplitude } from "@/amplitude/amplitude";

const notoSans = Noto_Serif({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: "600",
});

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Leaf & Life",
  description: "Generated by create next app",
  icons: {
    icon: "https://res.cloudinary.com/dryw0xncr/image/upload/v1779884659/leaf-svgrepo-com_dw9kig.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSans.variable} ${jakartaSans.variable} bg-primary antialiased`}
      data-scroll-behavior="smooth"
    >
      <Amplitude />
      <body className="flex flex-col max-w-7xl mx-auto ">
        {children}
      </body>
    </html>
  );
}
