import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Noto_Serif } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const notoSans = Noto_Serif({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: "600",
});

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSans.variable} ${jakartaSans.variable} bg-primary antialiased`}
      data-scroll-behavior="smooth"
    >
      <body className="flex flex-col max-w-7xl mx-auto ">
        {children}
      </body>
    </html>
  );
}
